# This script will download the videos by using pytube
# The videos will be saved into "/data"

# import packages
from __future__ import unicode_literals
from pytube import *
import pandas as pd

# initialize variables
# set up the path to save videos
save_path = "data/"

# initialize the csv file generated by "Get_URL.py"
# read it as dataframe and get all the links
videos_link_file = "data/videos_link.csv"
vl_DF = pd.read_csv(videos_link_file)
vl_list = vl_DF['link']

# use for loop to download all the videos and save them into "/data"
for item in vl_list:
    print(item)
    yt = YouTube(item)
    print(yt.title)
    # download video
    stream = yt.streams.first()
    stream.download(save_path)
    print('Finish')









