# This script will download the videos by using youtube-dl

# import packages
import pandas as pd
import os

# initialize the csv file generated by "Get_URL.py"
# read it as dataframe and get all the links
videos_link_file = "data/videos_link.csv"
vl_DF = pd.read_csv(videos_link_file)
vl_list = vl_DF['link']

# use for loop to download all the videos and save them into "/data"
for item in vl_list:
    print("Start to download: " + item)
    os.system('youtube-dl {}'.format(item))
    print('Finish!')









